# Generated by Django 4.2.2 on 2023-06-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(upload_to='')),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
    ]
